### ISSUE TITLE
dcl pack not working from Windows machines

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/dapps-issues#4]
I used the same smart item, same CLI version, ran `dcl pack` in a windows and in a mac, and the output was different. The output of the windows version is not accepted by the Builder when trying to import.

At least two people from the community have ran into this problem in the past few days.

To reproduce:
1) I took the `teleport-genesis` smart item from
https://github.com/decentraland/smart-items
2) Updated the decentraland-ecs version to latest
3) Ran dcl start, the preview worked well in both cases
4) Ran dcl pack
5) Tried to import the zip file into the builder

The version packed in the windows machine can't be imported when creating a new asset pack. It says "Invalid asset".

In both machines I'm using CLI version 3.4.9

The zip file produced is clearly different. The windows-packed version it includes game.ts, the mac-packed version doesn't. game.ts shouldn't be there in the zip.

Packed in mac: (working)
[https://app.zenhub.com/files/337227404/dd310532-9f97-4d31-9357-b2c8fcbe88b7/download](https://app.zenhub.com/files/337227404/dd310532-9f97-4d31-9357-b2c8fcbe88b7/download)

Packed in windows (not working)
[https://app.zenhub.com/files/337227404/3109df47-9668-4ec1-954f-07bc8c98e82a/download](https://app.zenhub.com/files/337227404/3109df47-9668-4ec1-954f-07bc8c98e82a/download)

**Comment by cazala** [comment]
Makes sense: the bundler produces comments to separate the files, and we use a RegEx to separate the transpiled files from the ECS files. The RegEx searches for files within the `src` folder by looking for `src/` but on Windows the comments produced by the bundler look like `src\` (inverse slash bar) so it fails to match it. 

To fix this we need to make the RegEx match both slash bars and inverse slash bars.

**Comment by cazala** [comment]
I deployed a fix for the reverse slash issue. That should fix smart items compiled on windows machines. Although there were two issues with the smart item, the other one was that it included the game.ts file. That file should not be part of the zip file, and the CLI should not include it. I dunno how it end up there, if it was generated using the `dcl pack` command then we should check why it included it (it should not do that, and the last time I used it, it didn't do that). One way to fix this is just removing the `src/game.ts` file from the zip. I did that and after this fix I can import it with no problems on the Builder.

**Comment by nearnshaw** [comment]
The game.ts seems to be always added in when you run `dcl pack` on a windows machine from what I tested. So yeah, that should also be fixed on the CLI.  Telling people to manually remove game.ts is a workaround, but not a pretty solution at all.

**Comment by cazala** [comment]
okay, yeah maybe it only happens on windows, maybe due to the same issue of the reverse slash, since it has an `if` to skip that file, but maybe the `if` doesn't match on windows. But yeah, to fix it we need to make changes to the CLI.

**Comment by cfravel** [comment]
This is still not fixed in 3.5.1. at ;least not on Windows.
At the least it shouldn't put src/gamet.ts (the test harness) into the item.zip file, because it makes it throw an error when adding it to an asset pack.

Other files that it tends to put into it that can/should be removed include
- .git folder, if you are using git
- .gitignore

I'm not sure, but probably package.json and .dclignore could be removed.
I like it that it puts any README.md into the item.zip, though.
