### ISSUE TITLE
Wrong owner in the map view

### ISSUE THREAD

**Issue by nachomazzara** [decentraland/dapps-issues#73]
In the marketplace, if I hover lands/estates, I see the wrong owner https://images.zenhubusercontent.com/359906797/647e3baf-e7db-4026-9cba-ed3ff8614dee/screen_recording_2023_07_24_at_09_32_24.mov

**Comment by LautaroPetaccio** [comment]
Closing this issue in favor of: https://github.com/decentraland/atlas-server/issues/96
